# -*- coding: utf-8 -*-
"""My Project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NM_3HOS1yD6pcfQxcvvtlJaj77ivu_wC
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

# 1. Sigmoid Function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# 2. Logistic Regression Scratch Implementation
class MyLogisticRegression:
    def __init__(self, learning_rate=0.01, iterations=1000):
        self.lr = learning_rate
        self.iterations = iterations
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        # Gradient Descent
        for _ in range(self.iterations):
            model_prediction = np.dot(X, self.weights) + self.bias
            predictions = sigmoid(model_prediction)

            # Gradient calculation
            dw = (1 / n_samples) * np.dot(X.T, (predictions - y))
            db = (1 / n_samples) * np.sum(predictions - y)

            # Update weights and bias
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        model_prediction = np.dot(X, self.weights) + self.bias
        predictions = sigmoid(model_prediction)
        return [1 if i > 0.5 else 0 for i in predictions]

# 3. Data preparation (Iris dataset - Binary classification)
iris = datasets.load_iris()
X = iris.data[:, :2] # Two features for visualization
y = (iris.target != 0) * 1 # 0 and 1 classes

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Training Custom Model
scratch_model = MyLogisticRegression(learning_rate=0.1, iterations=5000)
scratch_model.fit(X_train, y_train)
scratch_preds = scratch_model.predict(X_test)

# 5. Training Scikit-learn Model
sk_model = LogisticRegression()
sk_model.fit(X_train, y_train)
sk_preds = sk_model.predict(X_test)

# 6. Performance Comparison
print("--- Comparison Metrics ---")
print(f"Scratch Accuracy: {accuracy_score(y_test, scratch_preds):.2f}")
print(f"Sklearn Accuracy: {accuracy_score(y_test, sk_preds):.2f}")
print(f"Scratch Precision: {precision_score(y_test, scratch_preds):.2f}")
print(f"Sklearn Precision: {precision_score(y_test, sk_preds):.2f}")