# -*- coding: utf-8 -*-
"""My Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naN4oK1dbd3SThhyQW0XwYmFY4U-q9g_
"""

import numpy as np
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression as SklearnLogistic
from sklearn.metrics import accuracy_score, precision_score, recall_score

# 1. Dataset Generation
X, y = make_blobs(n_samples=500, centers=2, cluster_std=2.5, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Custom Logistic Regression Implementation
class CustomLogisticRegression:
    def __init__(self, learning_rate=0.01, iterations=1000):
        self.lr = learning_rate
        self.iterations = iterations
        self.weights = None
        self.bias = None

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.iterations):
            # Linear model prediction
            linear_model = np.dot(X, self.weights) + self.bias
            # Apply Sigmoid
            y_predicted = self._sigmoid(linear_model)

            # Gradient Descent
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            # Update parameters
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self._sigmoid(linear_model)
        # Threshold at 0.5 for binary classification
        return [1 if i > 0.5 else 0 for i in y_predicted]

# 3. Model Training & Evaluation
custom_model = CustomLogisticRegression(learning_rate=0.1, iterations=1000)
custom_model.fit(X_train, y_train)
custom_preds = custom_model.predict(X_test)

# 4. Scikit-learn Baseline
sklearn_model = SklearnLogistic()
sklearn_model.fit(X_train, y_train)
sklearn_preds = sklearn_model.predict(X_test)

# Compare Metrics
print(f"Custom Model - Accuracy: {accuracy_score(y_test, custom_preds):.4f}")
print(f"Sklearn Model - Accuracy: {accuracy_score(y_test, sklearn_preds):.4f}")